// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `activate_aumid`, `cached_pidl`, `cached_target`, `co_free`, `find_flutter_window`, `hbitmap_to_rgba`, `invoke_default_verb`, `is_noise`, `item_display_name`, `looks_like_aumid`, `main_window`, `new`, `parse_guid`, `pidl_byte_len`, `pidl_from_bytes`, `pidl_to_vec`, `plan_for`, `resolve_target`, `shell_execute_with`, `shell_execute`, `shell_item_for`, `shell_item_from_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ComScope`, `LaunchPlan`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`

/// 枚举 `shell:AppsFolder` 中的全部应用（等价于「开始菜单 → 所有应用」）。
Future<List<AppEntry>> listApps() =>
    RustLib.instance.api.crateApiLauncherListApps();

/// 提取指定应用的高清图标（最长边约 256px 的 RGBA 位图）。
///
/// `id` 为 [`list_apps`] 返回的 `AppEntry::id`。
Future<IconBitmap> loadIcon({required String id}) =>
    RustLib.instance.api.crateApiLauncherLoadIcon(id: id);

/// 启动应用。
///
/// AppsFolder 中的条目未必对应真实文件路径，因此按可靠性依次尝试多种方式。
Future<void> launchApp({required String id}) =>
    RustLib.instance.api.crateApiLauncherLaunchApp(id: id);

/// 诊断用：返回该应用会采用的启动方式，便于在 UI 中排查问题。
Future<String> launchPlan({required String id}) =>
    RustLib.instance.api.crateApiLauncherLaunchPlan(id: id);

/// 在资源管理器中定位该应用的可执行文件 / 快捷方式。
Future<void> revealInExplorer({required String id}) =>
    RustLib.instance.api.crateApiLauncherRevealInExplorer(id: id);

/// 返回当前桌面壁纸的文件路径（不可用时返回空串）。
Future<String> desktopWallpaper() =>
    RustLib.instance.api.crateApiLauncherDesktopWallpaper();

/// 无边框全屏（覆盖任务栏并置于最前），`enabled = false` 时还原。
Future<void> setFullscreen({required bool enabled}) =>
    RustLib.instance.api.crateApiLauncherSetFullscreen(enabled: enabled);

/// 退出全屏并恢复成居中的普通窗口（设置页用）。
///
/// 与 `set_fullscreen(false)` 的区别：这里会把窗口尺寸真正还原成给定值，
/// 否则窗口会保持「显示器大小 + 标题栏」，底部的按钮可能被挤到屏幕外。
Future<void> setWindowed({required int width, required int height}) => RustLib
    .instance
    .api
    .crateApiLauncherSetWindowed(width: width, height: height);

/// 让窗口重新获得前台焦点（用于从最小化恢复）。
Future<void> focusWindow() =>
    RustLib.instance.api.crateApiLauncherFocusWindow();

/// 隐藏窗口，进程留在后台以便热启动。
Future<void> hideWindow() => RustLib.instance.api.crateApiLauncherHideWindow();

/// 显示并置前窗口（热启动）。
Future<void> showWindow() => RustLib.instance.api.crateApiLauncherShowWindow();

/// 窗口当前是否可见（用于判断是否从托盘被重新呼出）。
Future<bool> isWindowVisible() =>
    RustLib.instance.api.crateApiLauncherIsWindowVisible();

/// 真正退出进程。
Future<void> quitApp() => RustLib.instance.api.crateApiLauncherQuitApp();

/// 弹出系统「打开文件」对话框，返回用户选中的可执行文件 / 快捷方式路径。
///
/// 用户取消时返回空列表。
Future<List<String>> pickFiles() =>
    RustLib.instance.api.crateApiLauncherPickFiles();

/// 返回用于缓存图标/布局的本地目录（`%LOCALAPPDATA%\\WindowsLauncherPad`），不存在则创建。
Future<String> dataDir() => RustLib.instance.api.crateApiLauncherDataDir();

/// 当前显示器主屏尺寸（物理像素），用于窗口初始化。
Future<(int, int)> primaryScreenSize() =>
    RustLib.instance.api.crateApiLauncherPrimaryScreenSize();

/// 一个可在启动台中展示的应用。
class AppEntry {
  /// 稳定且唯一的标识（`shell:AppsFolder` 中的解析名，UWP 即 AUMID）。
  final String id;

  /// 展示名称。
  final String name;

  /// 应用来源。
  final AppKind kind;

  /// 排序用关键字（小写）。
  final String sortKey;

  /// 解析后的真实启动目标；无法解析为文件路径时与 `id` 相同（即 AUMID）。
  final String target;

  const AppEntry({
    required this.id,
    required this.name,
    required this.kind,
    required this.sortKey,
    required this.target,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      sortKey.hashCode ^
      target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          sortKey == other.sortKey &&
          target == other.target;
}

/// 应用来源类型。
enum AppKind {
  /// 传统 Win32 应用（快捷方式 / 可执行文件）。
  win32,

  /// UWP / MSIX 打包应用（通过 AUMID 激活）。
  uwp,
}

/// 原始 RGBA 位图，由 Dart 侧解码为 `ui.Image`。
class IconBitmap {
  final int width;
  final int height;

  /// 长度 = width * height * 4，通道顺序 RGBA。
  final Uint8List rgba;

  const IconBitmap({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconBitmap &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
